### PR TITLE
Switch from conda to venv for development env

### PR DESCRIPTION
**Pull request by bloomsa**
addresses #1294 

Upon doing this, the "happy path" is simpler but overall it feels a little more frail / platform dependent. I'm curious to hear thoughts on that tradeoff or any suggestions people have seen from other repos

### CODE REVIEW

**Comment by bloomsa** [comment]
marked as draft until I get the docs updated

**Comment by lresende** [comment]
Could you elaborate on the why?

**Comment by bloomsa** [comment]
@lresende beyond what is in issue [#1294](https://github.com/jupyter-server/enterprise_gateway/issues/1294)?

**Comment by lresende** [comment]
is there a way to make it a choice? instead of one or another?

**Comment by kevin-bates** [comment]
Or remove this topic altogether.  To my earlier point, the environment is up to the dev, so should we even bother with providing these trivial helper methods at all?  We can _document suggestions_, but do we need the make target helpers?

**Comment by bloomsa** [comment]
> We can document suggestions, but do we need the make target helpers?

I like this idea. I can update the docs to include suggestions for both venv and conda, but pull out the make targets altogether. On one hand, it feels kinda wrong to pull out something that already works, but my thinking behind it is that having the targets there makes it seem like conda is the _only_ way to build the local dev environment when that isn't really the case.

Are you both okay with that solution @lresende @kevin-bates

**Comment by kevin-bates** [comment]
Hi @bloomsa - I apologize for the delay.  I'm fine with documenting suggestions.  I just don't really see the utility of having helper targets at this point.

@lresende - do you have a strong objection?

**Comment by lresende** [comment]
@kevin-bates  Well, it looks like we have been there:
https://github.com/jupyter-server/enterprise_gateway/pull/1079

And than we came back:
https://github.com/jupyter-server/enterprise_gateway/pull/1108

Do you remember why we had to come back?

**Comment by kevin-bates** [comment]
It appears we have come full circle. :smile:  @bloomsa contributed https://github.com/jupyter-server/enterprise_gateway/pull/1107 to introduce only the helper targets, but then we hit a bit of a snafu due to other changes that #1108 fixed.

Given this, I think we can proceed with removing the helper targets and _documenting_ suggestions for setting up `conda`/`mamba` and `venv` environments - as discussed above.

@lresende, @bloomsa - does this sound like a plan?

**Pull request closed without merging**
