### PR TITLE
[WIP] Add support for Spark 3.0

### PR DESCRIPTION
**Pull request by lresende**

### CODE REVIEW

**Comment by abzymeinsjtu** [comment]
any updates?

**Comment by abzymeinsjtu** [comment]
i just build assembly from master branch of incubating-toree and make some change to build.sbt,
and it works

**Comment by abzymeinsjtu** [comment]
btw, toree jar resource on master branch doesn't exist now

https://archive.apache.org/dist/incubator/toree/0.4.0-incubating/toree/toree-assembly-0.4.0-incubating.jar

**Comment by lresende** [comment]
I have created a new Toree RC and updated this pr to point to the latest release candidate. I will move this out of WIP when the release is approved.

**Comment by rahul26goyal** [comment]
@lresende : will this change be backward compatible with Spark-2.x runtime?
Just trying to understand :)

**Comment by lresende** [comment]
> @lresende : will this change be backward compatible with Spark-2.x runtime? Just trying to understand :)

Let me try to answer your question. if you need Spark 2.x, then what we have today is good. For folks needing the new features from Spark 3.x then this will be needed, and by moving to Spark 3.x one will find Spark incompatible APIs.

**Comment by rahul26goyal** [comment]
thanks for the explanation..let me ask a follow up question @lresende  to be more clear:
Let's someone is using JEG (older version) to provide `Spark-2.x Scala runtime on Kubernetes` to their uses and now they need to upgrade the JEG to latest version and (say) this fix is also part of the latest offering. 
1. Will the newly deployed JEG be able to launch the spark 2.x scala kernel fine?
thanks

**Comment by kevin-bates** [comment]
Hi @rahul26goyal.

> Will the newly deployed JEG be able to launch the spark 2.x scala kernel fine?

I'm finding while working with #559 that an EG based on Spark 3.2 (and pod templates) can launch a kernel-scala image based on Spark 2.4.6 AND be able to leverage the kernel-pod template.

image


I don't want to make any guarantees here, but all signs are pointing in a positive direction.  The reason I make this "guarantee" comment is because there might be something in my env that is misleading things, but because my scala kernel image that IS based on Spark 3.2 is failing - due to the version of Scala not being 2.12 and given I can access the spark context using a Spark 2.4.6-based kernel image, is a good sign.

That said, I don't think we (EG) should be in the business of producing kernelspec _examples_ for different scala/spark versions and will likely move forward with 2.12/3.2.0 out-of-the-box.

@lresende - I'm finding the scala portion of #559 is predicated on this PR and wondering if these PRs should be combined or closely coordinated?  I'm in the process of updating #559 with pins to 2.4.6 for now and TODO markers to clean things up.

**Comment by lresende** [comment]
I have updated this to use the just built Toree RC and also rebased to the latest master, will play with it a little and move out of wip if things are looking good.  

FYI: @kevin-bates

**Comment by kevin-bates** [comment]
Hi @lresende - thanks for moving forward with the Toree work.  

I think this PR should also include the appropriate changes to reference the updated Toree when [building the demo-base image](https://github.com/jupyter-server/enterprise_gateway/blob/54c8e31d9b17418f35454b49db691d2ce5643c22/etc/docker/demo-base/Dockerfile#L137-L143).  The tag for this image should reflect whatever version of Spark we're going with for the 3.x and is then referenced when [building the eg-demo image](https://github.com/jupyter-server/enterprise_gateway/blob/54c8e31d9b17418f35454b49db691d2ce5643c22/etc/docker/enterprise-gateway-demo/Dockerfile#L4).

I'll try taking a swing at this right now but may need to leave it to you.

**Comment by kevin-bates** [comment]
This pull request has been combined with #559, which contained overlapped changes that interfered with successful builds - closing.

**Pull request closed without merging**
